version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 88
  skip_doc_coverage = ["module", "magic", "init"]
  additional_builtins = ["_", "pretty_output"]
  cyclomatic_complexity_threshold = "high"

[[transformers]]  
name = "black"  
enabled = true

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react","vue","angular"]
  environment = ["nodejs","jquery","browser","mongo"]
  cyclomatic_complexity_threshold = "high"
  style_guide = "standard"

[[transformers]]  
name = "prettier"
enabled = true

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[transformers]]  
name = "rustfmt"  
enabled = true

[[analyzers]]
name = "ruby"

  [analyzers.meta]
  cyclomatic_complexity_threshold = "high"

[[transformers]]  
name = "rubocop"  
enabled = true

[[analyzers]]
name = "cxx"

  [analyzers.meta]
  cyclomatic_complexity_threshold = "high"

[[transformers]]  
name = "clang-format"
enabled = true

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"
  cyclomatic_complexity_threshold = "high"

[[analyzers]]
name = "php"

  [analyzers.meta]
  cyclomatic_complexity_threshold = "high"

[[transformers]]  
name = "php-cs-fixer"  
enabled = true