name: Create Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref }}
          title: 'New Pull Request from ${{ github.ref }}'
          body: 'Please review and merge this PR.'
